version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.9"

sphinx:
  fail_on_warning: true
  configuration: docs/source/conf.py

python:
  install:
    # Equivalent to 'pip install .'
    - method: pip
      path: .
    # Equivalent to 'pip install -r docs/requirements.txt'
    - requirements: docs/requirements.txt